version: 2

updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
  assignees:
  - shamil

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly

  assignees:
  - shamil
